#' Write NAMESPACE file imports statements
#' 
#' Writes imports statements that can be included in a package's NAMESPACE
#' file.
#' 
#' The result is an approximation based upon the findings of
#' \code{\link{findExternalDeps}}. S4 class dependencies are embedded into
#' importClassesFrom statements, S4 methods dependencies are embedded into
#' importMethodsFrom statements, and all other dependencies are embedded into
#' importFrom statements.
#' 
#' See the document "Writing R Extensions" that is hosted on CRAN for more
#' details on the proper construction of a NAMESPACE file.
#' 
#' @param package the quoted name of the package to analyze.
#' @param file either a character string naming a file or an open writing
#' connection. \code{""} indicates writing to the console.
#' @param append logical. If \code{TRUE}, the output is appended to the file.
#' If \code{FALSE}, any existing file with the specified name is destroyed and
#' a new one is created. This argument is only used if \code{file} is a
#' character string.
#' @param quote logical. If \code{TRUE}, all import fields will be
#' double-quoted.  If \code{FALSE}, only non-standard names like
#' \code{[<-.fractions} will be double-quoted.
#' @param width a positive integer giving the target column for wrapping lines
#' in the output.
#' @author Patrick Aboyoun
#' @export
#' @seealso \code{\link{findExternalDeps}}
#' @keywords programming
#' @examples
#' 
#' library(stats4)
#' writeNamespaceImports("stats4")
#' 
writeNamespaceImports <-
    function(package, file = "", append = TRUE, quote = FALSE,
             width = 0.9 * getOption("width"))
{
    writeImports <- function(x, prefix, file, width) {
        Rkeywords <-
          c("NULL", "NA", "TRUE", "FALSE", "Inf", "NaN", "NA_integer_",
            "NA_real_", "NA_character_", "NA_complex_", "function", "while",
            "repeat", "for", "if", "in", "else", "next", "break", "...")
        for (i in which(!(names(x) %in% ignoredPackages))) {
            if (quote) {
                qstring1 <- "\""
                qstring2 <- "\""
            } else {
                qstring1 <- ""
                qstring2 <- ifelse(x[[i]] %in% Rkeywords, "\"", "")
                qstring2[grep("(<-|\\[|%)", x[[i]])] <- "\""
            }
            txt <- paste0(prefix, "(", qstring1, names(x[i]), qstring1, ", ",
                          paste0(qstring2, x[[i]], qstring2, collapse = ", "),
                          ")")
            cat(strwrap(txt, width = width, exdent = nchar(prefix) + 1),
                file = file, sep = "\n")
            cat("\n", file = file)
        }
    }
    ignoredPackages <- c("base", "Autoloads")
    if (file == "")
        file <- stdout()
    else if (is.character(file)) {
        file <- file(file, ifelse(append, "a", "w"))
        on.exit(close(file))
    }
    else if (!isOpen(file, "w")) {
        open(file, "w")
        on.exit(close(file))
    }
    if (!inherits(file, "connection"))
        stop("'file' must be a character string or connection")

    allDeps <- findExternalDeps(package)
    allDepNames <- sort(unique(ulapply(allDeps, names)))
    allDepNames <- allDepNames[!(allDepNames %in% ignoredPackages)]
    if (length(allDepNames) > 0) {
        hasNamespace <- vapply(allDepNames, function(x)
            !identical(FALSE, tryCatch(getNamespace(x), error = function(e) FALSE)), NA)
        dependsNames <- allDepNames[!hasNamespace]
        importsNames <- allDepNames[hasNamespace]
        ignoredPackages <- c(ignoredPackages, dependsNames)
        cat("#Generated by codetoolsBioC version ",
            packageDescription("codetoolsBioC")[["Version"]], "\n",
            file = file, sep = "")
        cat("#Timestamp: ", date(), "\n\n", file = file, sep = "")
        if (length(dependsNames) > 0) {
            txt <- paste0("Depends: ", paste(dependsNames, collapse = ", "))
            cat(strwrap(txt, width = width, exdent = 9, prefix = "#"),
                file = file, sep = "\n")
            cat("\n", file = file)
        }
        if (length(importsNames) > 0) {
            txt <- paste0("Imports: ", paste(importsNames, collapse = ", "))
            cat(strwrap(txt, width = width, exdent = 9, prefix = "#"),
                file = file, sep = "\n")
            cat("\n", file = file)
        }
        writeImports(allDeps[["S4Classes"]], "importClassesFrom", file, width)
        writeImports(allDeps[["S4Methods"]], "importMethodsFrom", file, width)
        writeImports(allDeps[["functions"]], "importFrom", file, width)
        writeImports(allDeps[["variables"]], "importFrom", file, width)
    }
}
